[package]
name = "my_cool_package"
authors = ["wujek m"]
compiler_version = ">=0.18.0"
version = "0.0.2"
type = "lib"

[dependencies]
aztec = { path = "../aztec" }
value_note = { path = "../value-note" }